# Generated by Django 4.2.5 on 2023-09-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cenexfront', '0002_remove_userinfo_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
    ]
