# Generated by Django 4.2.5 on 2023-09-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenexfront', '0003_remove_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='company_name',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
    ]
